name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{ cron: "0 7 * * *" }]

  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
  release:
    types: [published]
jobs:
  github-metrics:
    runs-on: ubuntu-20.04
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.REPOSITORY_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: luisfalconmx
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Mexico_City
          plugin_followup: yes
          plugin_gists: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
